CREATE TABLE t_dwa_zcsd_user_log_summary (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	uid varchar(50) DEFAULT NULL,
	cid varchar(50) DEFAULT NULL,
	pid varchar(50) DEFAULT NULL,
	ts datetime DEFAULT NULL,
	ts_str varchar(50) DEFAULT NULL,
	lat_str varchar(50) DEFAULT NULL,
	lon_str varchar(50) DEFAULT NULL,
	op varchar(50) DEFAULT NULL,
	cnt int(11) DEFAULT NULL,
	nickname varchar(50) DEFAULT NULL,
	phone varchar(20) DEFAULT NULL,
	age varchar(50) DEFAULT NULL,
	sex varchar(50) DEFAULT NULL,
	company varchar(100) DEFAULT NULL,
	duty varchar(100) DEFAULT NULL,
	title varchar(200) DEFAULT NULL,
	label_industry_ids varchar(200) DEFAULT NULL,
	label_place_ids varchar(200) DEFAULT NULL,
	location varchar(100) DEFAULT NULL,
	KEY `idx_id` (`id`),
	KEY `idx_cid` (`cid`),
	KEY `idx_uid` (`uid`),
	KEY `idx_phone` (`phone`),
	KEY `idx_ts` (`ts`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='政策速递用户行为汇总表';